#!/bin/bash
# A. frostiana - no seqs 
# A. regalis 
MH509023.1
# A. persicina 
EU071877.1
EU071862.1
EU071861.1
EU071859.1
# A. chrysoblema (= A. muscaria var. alba s. Jenkins non s. auct. europaeis) - no seqs
# A. muscaria var. guessowii 
EU071863
EU071864
EU071875
# A. muscaria subsp. flavivolvata
EU071860
EU071865
# A. muscaria var. formosa (= A. muscaria f. formosa?) - no seqs 
# A. muscaria var. muscaria
EU071874
EU071868.1
EU071867.1
EU071866.1
EU071865.1
EU071864.1
EU071863.1
EU071860.1
EU071878.1
EU071876.1
EU071879.1
EU071883.1
EU071875.1
# A. gioiosa - no seqs
# A. breckonii - no seqs 
# A. ameripantherina nom. prov. s. RET - no seqs available
# A. subvelatipes n.p. s. RET - no seqs available 
# A. velatipes
MH509155.1
# A. tlaxcalipanthera - no seqs
# A. wellsii - no seqs 
# A. austrowellsii - no seqs
# A. parcivolvata - no seqs
# A. rubescens
MH509043.1
MH509042.1
MH509041.1
MH509040.1
MH509039.1
MH509038.1